#!/bin/bash

# Layout prefix is prepended to each markdown file synced
###################################################################
LAYOUT_PREFIX='---\nlayout: index\n---\n'

# Sync the README.md in master to index.md adding jekyll header
###################################################################
echo -e $LAYOUT_PREFIX > index.md
git show master:README.md >> index.md
git commit index.md -m "Sync README.md in master branch to index.md in gh-pages"
    
git push 
